### ISSUE TITLE
Photos are not Showing,

### ISSUE THREAD

**Issue by MahendraBishnoi29** [trananhtuat/react-movie#1]
**Photos are not Showing on HeroSlider , api is correct i'm getting them in console but they aren't showing on app.**

![Screenshot (61)](https://user-images.githubusercontent.com/74294202/139523295-abb9babc-4742-417f-be50-23cd43ae79dd.png)
Console Details 👇
![Screenshot (62)](https://user-images.githubusercontent.com/74294202/139523302-379c8b61-3f06-48a4-a6be-a86948c8f4d9.png)

*HeroSlider.js Code* 👇

`const HeroSlide = () => {
  SwiperCore.use([Autoplay]);

  const [movieItems, setMovieItems] = useState([]);

  useEffect(() => {
    const getMovies = async () => {
      const params = { page: 1 };
      try {
        const response = await tmdbApi.getMoviesList(movieType.popular, {
          params,
        });
        setMovieItems(response.results?.slice(1, 4));
        console.log(response);
      } catch (error) {
        console.log(error.message);
      }
    };
    getMovies();
  }, []);

  return (
    <div className="hero-slide">
      <Swiper
        modules={[Autoplay]}
        grabCursor={true}
        spaceBetween={0}
        slidesPerView={1}
        autoplay={{ delay: 3000 }}
      >
        {movieItems?.map((item, i) => (
          <SwiperSlide key={i}>
            {({ isActive }) => (
              <HeroSlideItem
                item={item}
                className={`${isActive ? "active" : ""}`}
              />
            )}
          </SwiperSlide>
        ))}
      </Swiper>
    </div>
  );
};

const HeroSlideItem = (props) => {
  let hisrory = useHistory();

  const item = props.item;

  const background = apiConfig.originalImage(
    item?.backdrop_path ? item?.backdrop_path : item.poster_path
  );

  return (
    <div
      className={`hero-slide__item ${props.className}`}
      style={{ backgroundImage: `url(${background})` }}
    >
      <div className="hero-slide__item__content container">
        <div className="hero-slide__item__content__info">
          <h2 className="title">{item.title}</h2>
          <div className="overview">{item.overview}</div>
          <div className="btns">
            <Button onClick={() => hisrory.push("/movie/" + item.id)}>
              Watch now
            </Button>
            <OutlineButton>Watch trailer</OutlineButton>
          </div>
        </div>
        <div className="hero-slide__item__content__poster">
          <img src={apiConfig.w500Image(item?.poster_path)} alt="" />
        </div>
      </div>
    </div>
  );
};

export default HeroSlide;
`

**Comment by Aarekaz** [comment]
@trananhtuat  Any update?

**Comment by MahendraBishnoi29** [comment]
yes actually it was my mistake u have to write ".data" in front of every api Property like for poster "apiConfing.data.poster_path" and it will work. let me know about any error i'hve completed this project.

**Comment by Aarekaz** [comment]
![unknown](https://user-images.githubusercontent.com/36888347/146876658-0100af15-e91d-4164-9a5c-59e3dd191b01.png)
I have this error while trying to watch videos or opening video link in movie detail page.,
![image](https://user-images.githubusercontent.com/36888347/146877857-abf30f5c-01c6-4c21-b558-74ed36f786d6.png)

note:my API is mmlAPI

**Comment by MahendraBishnoi29** [comment]
> ![unknown](https://user-images.githubusercontent.com/36888347/146876658-0100af15-e91d-4164-9a5c-59e3dd191b01.png) I have this error while trying to watch videos or opening video link in movie detail page., ![image](https://user-images.githubusercontent.com/36888347/146877857-abf30f5c-01c6-4c21-b558-74ed36f786d6.png)
> 
> note:my API is mmlAPI
 
Your ScreenShot is Not Clear

**Comment by MahendraBishnoi29** [comment]
Give Me Your Github Repo

**Comment by Aarekaz** [comment]
I fixed it. It's working now. Thank you

**Comment by sudiptapradhan** [comment]
> yes actually it was my mistake u have to write ".data" in front of every api Property like for poster "apiConfing.data.poster_path" and it will work. let me know about any error i'hve completed this project.

still not working :)
i mean the photo still doesn't show 
can anyone help!
@Aarekaz @MahendraBishnoi29

**Comment by MahendraBishnoi29** [comment]
sure @sudiptapradhan what's the problem
